const TODO_STATUS = {
  PENDING: 'pending',
  IN_PROGRESS: 'in-progress',
  DONE: 'done'
};

const TODO_TITLE_MAX_LENGTH = 255;

const USER_ROLES = {
  USER: 'user',
  ADMIN: 'admin'
};

const PASSWORD_MIN_LENGTH = 8;
const PASSWORD_MAX_LENGTH = 64;
const USERNAME_MIN_LENGTH = 2;
const USERNAME_MAX_LENGTH = 30;



module.exports = {
  TODO_STATUS,
  TODO_TITLE_MAX_LENGTH,
  USER_ROLES,
  PASSWORD_MIN_LENGTH,
  PASSWORD_MAX_LENGTH,
  USERNAME_MIN_LENGTH,
  USERNAME_MAX_LENGTH
};